image: Visual Studio 2015

stack: node 10

branches:
  only:
  - master

cache: node_modules

install:
- yarn add

build: off

build_script:
- yarn run build

test_script:
- yarn run lint && yarn test